bin: report http errors in `emby`

diff --git a/bin/emby b/bin/emby
--- a/bin/emby
+++ b/bin/emby
@@ -479,17 +479,25 @@ api() {
     set -- -G "$@"
   fi
 
-  local response
+  local response status body
 
   response=$(curl --silent \
+    --write-out "\n%{http_code}" \
     --header "Accept: */*" \
     --header "Content-Type: application/json" \
     "$@" \
     "${EMBY_API_URL%%/}/emby/$path?api_key=$EMBY_API_KEY"
   )
 
-  if ! jq . <<< "$response" 2> /dev/null; then
-    cat <<< "$response"
+  status=$(sed -n '$p' <<< "$response")
+  body=$(sed '$d' <<< "$response")
+
+  if [[ "$status" -ge 400 ]]; then
+    echo "Error: $status" >&2
+  fi
+
+  if ! jq . <<< "$body" 2> /dev/null; then
+    cat <<< "$body" | sed "s/&#39;/'/g"
   fi
 }
 
