bin: let gcof take a branch name and just check it out

diff --git a/bin/gcof b/bin/gcof
--- a/bin/gcof
+++ b/bin/gcof
@@ -28,8 +28,14 @@ while [ $# -gt 0 ]; do
     static=1
     ;;
   *)
-    help >&2
-    exit 1
+    if [[ "$#" == 1 ]]; then
+      git checkout "$1"
+      exit 1
+    else
+      echo "error: unknown argument: $1" >&2
+      help >&2
+      exit 1
+    fi
     ;;
   esac
   shift
