opt: cleanup viscosity

diff --git a/opt/macos-scripts/bin/viscosity b/opt/macos-scripts/bin/viscosity
--- a/opt/macos-scripts/bin/viscosity
+++ b/opt/macos-scripts/bin/viscosity
@@ -13,12 +13,14 @@
 #   viscosity remember-username     Remember username (but not password)
 #   viscosity help                  Show this help message
 
-if [[ "${DEBUG}" ]]; then
+if [[ "$DEBUG" ]]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
 
-case "${1}" in
+set -e
+
+case "${1-}" in
   ""|-h|--help|help)
     sed -ne '/^#/!q;s/^#$/# /;/^# /s/^# //p' < "$0" |
       awk -v f="${1//-/}" 'f == "h" && $1 == "Usage:" { print; exit }; f != "h"'
@@ -29,15 +31,15 @@ case "${1}" in
     exit
     ;;
   connect|disconnect)
-    if [[ -z "${2}" ]]; then
+    if [[ -z "$2" ]]; then
       osascript -e "tell application \"Viscosity\" to ${1}all"
     else
-      osascript -e "tell application \"Viscosity\" to ${1} \"${2}\""
+      osascript -e "tell application \"Viscosity\" to $1 \"$2\""
     fi
     ;;
   status)
-    if [[ "${2}" ]]; then
-      osascript -e "tell application \"Viscosity\" to return state of (connections where name is \"${2}\")"
+    if [[ "$2" ]]; then
+      osascript -e "tell application \"Viscosity\" to return state of (connections where name is \"$2\")"
     else
       osascript -e '
         tell application "Viscosity"
@@ -58,7 +60,7 @@ case "${1}" in
     fi
     ;;
   *)
-    echo "Invalid command ${1}"
+    echo "Invalid command $1"
     exit 1
     ;;
 esac
